### PR TITLE
Introduce docs

### PR DESCRIPTION
**Pull request by anriseth**
Here's an attempt at introducing documentation in combination with Literate examples.

I propose that we introduce docs in three steps (if you are okay with making docs this way @pkofod )
1. Merge this and check out what the docs look like
2. Move the Optim examples in the README to a Literate.jl example
3. Possibly write a larger manual for each of the line search methods (and step length guesses)

### CODE REVIEW

**Comment by anriseth** [comment]
I put the Documenter script call in `runtests.jl`.

Let me know if you prefer that it is added as a separate call in `.travis.jl` in the same fashion as we do in `Optim.`

**Comment by pkofod** [comment]
Won’t it deploy in all builds then?

**Comment by anriseth** [comment]
> Won’t it deploy in all builds then?

Hmm, I don't know. I just saw that this is how they do it in `JuAFEM`. 

@KristofferC @fredrikekre is there a benefit in calling `Documenter` from `runtests.jl` rather than in `.travis.jl`?

**Comment by fredrikekre** [comment]
> is there a benefit in calling Documenter from runtests.jl rather than in .travis.jl?

The benefit is that if the doc-build fail (for any reason, for example doctests) then the CI run is marked as a fail. Steps that fail in `after_success` on travis does not mark the build as a fail.) The other advantage is that you can put Documenter in `test/REQUIRE` and it will be installed automatically withouth manual `Pkg.add`'s.

>Won’t it deploy in all builds then?

We do this:
https://github.com/KristofferC/JuAFEM.jl/blob/fb3cc17a57f54ac89a137d80fa85328e082dda0b/test/runtests.jl#L21
to only run docs on one worker.

**Comment by anriseth** [comment]
Thanks for the input :)

I use the same Travis build check as JuAFEM, so it sounds like the setup in this PR works fine.

**Comment by fredrikekre** [comment]
Need to add a SSH-key to Travis (https://juliadocs.github.io/Documenter.jl/latest/man/hosting/)
```
Warning: DOCUMENTER_KEY environment variable missing, unable to deploy.
  Note that in Documenter v0.9.0 old deprecated authentication methods were removed.
  DOCUMENTER_KEY is now the only option. See the documentation for more information.
```

**Comment by pkofod** [comment]
should be added now

**Comment by fredrikekre** [comment]
Cool: https://julianlsolvers.github.io/LineSearches.jl/latest/

I just wanted to see how it worked out with Literate! 😄

**Comment by anriseth** [comment]
Yes, it seems to work well :D 

Haha, I kept the line from JuAFEM, woops.

> and then run
```jl
using JuAFEM
```

**Comment by pkofod** [comment]
Seems to work just fine! Awesome. I'll have @iewaij add his coming Optim examples using `Literate.jl` as well

**Comment by pkofod** [comment]
> Haha, I kept the line from JuAFEM, woops.

Let's just add JuAFEM to require then ;)

**Pull request merged**
