### PR TITLE
Adhere to new storage/x argument order, and bump NLSolversBase versio…

### PR DESCRIPTION
**Pull request by pkofod**
…n to 2.0.0 and up.

This is all there is to it I guess? I mean, we kind of created NLSolversBase such that changes like the one we are facing wouldn't really matter in this code.

### CODE REVIEW

**Comment by pkofod** [comment]
Hm, we don't have AV ci here?... We should

**Comment by pkofod** [comment]
@anriseth do you agree that nothing substantial needs to be changed besides the tests? After we make the change in Optim we should enable the Optim tests again.

**Comment by anriseth** [comment]
Thanks. Yeah with the value and grad api in Base, the tests are the only thing that needs changing.
But we will need to make sure all packages that rely on LineSearches and Base have the correct upper limits. I think that's only Optim for now?

**Comment by pkofod** [comment]
I think nlsolve has the correct upper bound. Wasn't that what we went through in metadata the other week?

**Comment by anriseth** [comment]
Yep, they're still on pre-v1.0.

I'll merge this now

On Thu, 6 Apr 2017, 18:00 Patrick Kofod Mogensen, <notifications@github.com>
wrote:

I think nlsolve has the correct upper bound. Wasn't that what we went
through in metadata the other week?

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/JuliaNLSolvers/LineSearches.jl/pull/38#issuecomment-292238343>,
or mute the thread

**Comment by anriseth** [comment]
Hmm, I don't understand why the Travis push test fails, whilst the Travis pr test works?

**Comment by pkofod** [comment]
Oh, that doesn't matter, it's just because it's targeting a different master than current master, and I removed the optim dependency in tests after I created this pr, because we're not using them yet.

**Comment by pkofod** [comment]
just to prove that it was okay: https://travis-ci.org/JuliaNLSolvers/LineSearches.jl :)

**Pull request merged**
