### PR TITLE
[WIP] Fix HagerZhang bugs

### LINKED ISSUE #133: Initial HagerZhang: norm(gr) -> norm(gr)^2
https://github.com/JuliaNLSolvers/LineSearches.jl/blob/1f40bf319887b77f66f89154763b5d49924894a7/src/initialguess.jl#L292

In the paper, the divisor is `norm(gr)^2`

### PR DESCRIPTION
**Pull request by mohamed82008**
This PR closes #133, #134, and #135. There is one error I am getting in LineSearches tests which seems unrelated to the changes made. Optim tests pass. I will look into this further. Also, I need to check if other places error when the search direction is not a descent direction and try to make it robust to computational error when starting at the optimal solution. Finally, someone please comment on my use of `mayterminate` since I don't understand how it will be used apart from checking when the quadratic step is taken.

### CODE REVIEW

**Comment by mohamed82008** [comment]
I think this is good to go with the exception of some tests failing. The tests maybe depending on the old behavior? Does that make them good tests? Any help there is appreciated. Optim tests pass, so that's a sign that I didn't totally screw up.

**Comment by pkofod** [comment]
I think that test is probably just check that behavior hasn't changed, but it seems quite likely that your changes come with changes to that exact step length. I Don't have time right now, but I'll review asap.

**Comment by anriseth** [comment]
> The tests are maybe depending on the old behavior? Does that make them good tests?

Most are just to flag if we unintentionally change behaviour and are not good tests. They were added long after the implementation of the algorithms so little thought has been put into them. Feel free to update them if you believe the new behaviour is the correct one ;)

**Comment by mohamed82008** [comment]
All good now.

**Comment by pkofod** [comment]
Thanks! I believe code coverage is really bugged in julia these days..

**Comment by pkofod** [comment]
I've tagged a bugfix release https://github.com/notifications

**Comment by mohamed82008** [comment]
Awesome thanks for the quick merge!

**Pull request merged**
