### PR TITLE
Replace @simd loops

### PR DESCRIPTION
**Pull request by anriseth**

### CODE REVIEW

**Comment by pkofod** [comment]
Just for fun, did you try to benchmark it? I don't suspect a difference (at least not for the worse) just curious.

**Comment by anriseth** [comment]
I haven't benchmarked it. Blind faith ;)

**Comment by pkofod** [comment]
I like it!

**Comment by pkofod** [comment]
On a serious note I do find that the simd version is hard to predict perf on. In NelderMead it slowed some parts down. Guess I just don't know enough about simd vectorization.

**Pull request merged**
