### PR TITLE
v0.7 Depwarns

### PR DESCRIPTION
**Pull request by chriselrod**
This is tracking the Univariatize pull request:
https://github.com/JuliaNLSolvers/LineSearches.jl/pull/86

### CODE REVIEW

**Comment by pkofod** [comment]
I merged the PR, so we can resolve this now. The diff looks quite weird though, do you know what happened?

**Comment by chriselrod** [comment]
Not exactly. I'm new to `git` and made a few mistakes, and cleaning them up ruined the history.
I'll try and fix it.

**Comment by pkofod** [comment]
Ah okay, it's just slightly hard to figure out where your changes are :)

**Comment by chriselrod** [comment]
I messed things up pretty badly when trying to rebase on top of your changes, so I figured it was easiest to start fresh -- there weren't many changes, and the one that took time was just figuring out what to do in Hagerzhang.

**Pull request merged**
