### PR TITLE
Provide usage example with custom optimization algorithms

### PR DESCRIPTION
**Pull request by anriseth**
This provides an example of how to use LineSearches with algorithms that are not within the Optim/NLsolve universe.

I wrote it in the Literate.jl style, so that we can turn it into Docs or Notebooks to make it easier for people to try these things out.

This requires #90 and #106 to work.

### CODE REVIEW

**Comment by pkofod** [comment]
The line searchers aren't actually <: abstractlinesearch. Either you have to add that to the methods, or remove it in the signature.

Note that you have to pull my commit first.

**Comment by pkofod** [comment]
(I hope it's okay that I made the change myself)

**Comment by anriseth** [comment]
> (I hope it's okay that I made the change myself)

All good :)

I'll create a quick commit to change `ls` to `linesearch` for brevity.

**Comment by iwelch** [comment]
still doesn't work for me:

```
/tmp/linetest:0:526> julia customoptimizer.jl
ERROR: LoadError: MethodError: no method matching (::LineSearches.BackTracking{Float64,Int64})(::#ϕ#5{#f,Array{Float64,1}}, ::Float64, ::Float64, ::Float64)
Closest candidates are:
  BackTracking(::Any, ::Any, ::Any, ::Any, !Matched::Any, !Matched::Any, !Matched::Any) at /Users/ivo/.julia/v0.6/LineSearches/src/backtracking.jl:20
Stacktrace:
 [1] gdoptimize(::#f, ::#g!, ::#fg!, ::Array{Float64,1}, ::LineSearches.BackTracking{Float64,Int64}, ::Int64, ::Float64, ::Float64) at /private/tmp/linetest/customoptimizer.jl:41
 [2] gdoptimize(::Function, ::Function, ::Function, ::Array{Float64,1}, ::LineSearches.BackTracking{Float64,Int64}) at /private/tmp/linetest/customoptimizer.jl:13
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] process_options(::Base.JLOptions) at ./client.jl:305
 [6] _start() at ./client.jl:371
while loading /private/tmp/linetest/customoptimizer.jl, in expression starting on line 109
```

**Comment by anriseth** [comment]
> what installs without special changes on 0.6.3... 3.2.5 .

I see. Can you check out the `master` branch and try again, please?

LineSearches 3.2.5 is old, and we are currently on `v5.2.1`. Note that there are several (breaking) changes on `master` that are not in `v5` that will come to `v6.0.0.0`

**Comment by iwelch** [comment]
may I ask why you don't release a newer version to the general public?

**Comment by anriseth** [comment]
> may I ask why you don't release a newer version to the general public?

Because it is work-in-progress. 

> ERROR: Optim can't be installed because it has no versions that support 0.6.3 of julia. You may need to update METADATA by running `Pkg.update()`

Ah, sorry I should have emphasised that the stable releases of Optim may block the newest/development versions of LineSearches. It may be possible to fix those problems by checking out Optim `master` first, although the Julia package manager may end up in some version bound clusterfuck. I choose my branches manually by going to `~/.julia/v0.6/Optim` in the terminal.

**Comment by iwelch** [comment]
```
julia> Pkg.checkout("Optim")
INFO: Checking out Optim master...
INFO: Pulling Optim latest master...
WARNING: LineSearches is fixed at 3.2.5 conflicting with requirement for Optim: [5.2.0,∞)
ERROR: fixed packages introduce conflicting requirements for NLSolversBase:
         LineSearches requires versions [3.0.0,5.0.0)
         Optim requires versions [6.0.0,∞)
       the requirements are unsatisfiable because their intersection is empty
```

for now, this all seems quite involved.  I think I will wait until we get a stable Optim.jl and Linesearches.jl again.

can I ask a quick question?  can the linesearches functions deal with NaN region?  e.g., can I pass the `sqrt()` function and expect to get 0.0 back?

**Comment by pkofod** [comment]
> I think I will wait until we get a stable Optim.jl and Linesearches.jl again.

There *are* stable releases of Optim and  LineSearches, they are installed using `Pkg.add`. Of course, the development versions will always be ahead by definition.

 

> may I ask why you don't release a newer version to the general public?

We're always open to contributions from everyone! :) Stuff needs to fit together, work, be tested, yadada, and unfortunately this is not our source of income.

**Comment by iwelch** [comment]
hi p---of course.  I am tinkering on stuff that I hope will eventually go
into Optim.jl.  Alas, for now, I am still at square one.   I looked at the
code.  The way it fits together is somewhat involved.  It's not trivial to
make a small change.

can I ask a quick question? can the linesearches functions deal with NaN
region? e.g., can I pass the sqrt() function and expect to get 0.0 back?

--
Ivo Welch (ivo.welch@ucla.edu)
http://www.ivo-welch.info/
J. Fred Weston Distinguished Professor of Finance, UCLA Anderson
Free Corporate Finance Textbook, http://book.ivo-welch.info/
Exec Editor, Critical Finance Review,
http://www.critical-finance-review.org/
*[please acknowledge receipt if this is the first email in a conversation]*

**Comment by pkofod** [comment]
> can I ask a quick question? can the linesearches functions deal with NaN region? e.g., can I pass the sqrt() function and expect to get 0.0 back?

I seems that you have a specific example. Care to share?

**Pull request merged**
