### PR TITLE
Update backtracking

### PR DESCRIPTION
**Pull request by pkofod**
@anriseth 

this removes the unnecessary vector and renames some stuff.

### CODE REVIEW

**Comment by anriseth** [comment]
Looks like we're getting closer to a univariate interface :)

In terms of consistency across the algorithms, will \alpha_2 be easy to use as the representative of the "most recent guess" of the step length everywhere? (It's not really that crucial, but if we could use the same variable name for all algorithms that would be neat)

**Comment by pkofod** [comment]
> In terms of consistency across the algorithms, will \alpha_2 be easy to use as the representative of the "most recent guess" of the step length everywhere? (It's not really that crucial, but if we could use the same variable name for all algorithms that would be neat)

Would you rather \alpha_a, \alpha_b, \alpha_c, \alpha_d, .... for first, second, third, fourth, ... ?

**Comment by anriseth** [comment]
I like numbers better. Maybe we can just put a comment in the codes, for the user's benefit of understanding which variable is intended to be returned? (I know they can just look for return statements, but this helps with chronology when reading the code)

**Comment by pkofod** [comment]
So do you prefer `_1`, `_2`, ... ? In strongwolfe they're labelled `\alpha_i`, `alpha_iminus1`.

**Comment by anriseth** [comment]
I think I'll retract my wish for "consistency" :p 

Looking at HagerZhang, it seems difficult to unify the variable names in the different algorithms, so let's just go with whatever makes the most sense for each algorithm individually. As you are going through them now, I say you go with what is more readable to you.

There is also an advantage to using the same variables as used by the authors of the papers describing the algorithms, as it is easier to compare the papers/books with the code we have.

**Comment by pkofod** [comment]
> There is also an advantage to using the same variables as used by the authors of the papers describing the algorithms, as it is easier to compare the papers/books with the code we have.

I think this may be the best argument. Consistency where it makes sense, but fall back to paper / text book notation.

**Pull request merged**
