### PR TITLE
Simple example usage in the README

### PR DESCRIPTION
**Pull request by antoine-levitt**

### CODE REVIEW

**Comment by pkofod** [comment]
Huh, what's up with the tests...


(and thanks for the addition of an example)

**Comment by anriseth** [comment]
I just thought I'd try to re-run the tests, which didn't work  I'll leave it to you guys who still know what you're doing :p

**Comment by pkofod** [comment]
maybe it'll obey me @anriseth  ?

**Comment by pkofod** [comment]
(I fixed the problem which was in Optim :) )

**Pull request merged**
